# -*- coding: utf-8 -*-
"""this is final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wd2moWo6TlL4HEMx_pQqeufstTpP91vo
"""


import pandas as pd
import torch
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from transformers import (
AutoTokenizer,
AutoModelForSequenceClassification,
Trainer,
TrainingArguments
)

# LOAD DATASET
df = pd.read_csv("dataset.csv")

df.columns = ["Emotion","Sentence"]

# CLEAN LABELS
df["Emotion"] = df["Emotion"].str.lower().str.strip()

# LABEL ENCODING
le = LabelEncoder()

df['label'] = le.fit_transform(df['Emotion'])

# SAVE LABEL ENCODER
import pickle

pickle.dump(
le,
open("label_encoder.pkl","wb")
)

# REMOVE EMPTY ROWS
df = df.dropna()

# CONVERT TO STRING (IMPORTANT FIX)
df["Sentence"] = df["Sentence"].astype(str)

df["Emotion"] = df["Emotion"].astype(str)

# LOWERCASE TEXT
df["Sentence"] = df["Sentence"].str.lower()

# SPLIT DATA
train_texts, test_texts, train_labels, test_labels = train_test_split(

    df["Sentence"],

    df["label"],

    test_size=0.2,

    random_state=42

)

# TOKENIZER
tokenizer = AutoTokenizer.from_pretrained(

"j-hartmann/emotion-english-distilroberta-base"

)

# TOKENIZE
train_encodings = tokenizer(

list(train_texts),

truncation=True,

padding=True,

max_length=128

)

test_encodings = tokenizer(

list(test_texts),

truncation=True,

padding=True,

max_length=128

)

# DATASET CLASS
class EmotionDataset(torch.utils.data.Dataset):

    def __init__(self,encodings,labels):

        self.encodings = encodings

        self.labels = labels.reset_index(drop=True)

    def __getitem__(self,idx):

        item = {

        key: torch.tensor(val[idx])

        for key,val in self.encodings.items()

        }

        item["labels"] = torch.tensor(

        self.labels[idx]

        )

        return item

    def __len__(self):

        return len(self.labels)

train_dataset = EmotionDataset(

train_encodings,

train_labels

)

test_dataset = EmotionDataset(

test_encodings,

test_labels

)

# LOAD MODEL
model = AutoModelForSequenceClassification.from_pretrained(

"j-hartmann/emotion-english-distilroberta-base",

num_labels=len(le.classes_),

ignore_mismatched_sizes=True

)

# TRAINING SETTINGS
training_args = TrainingArguments(

output_dir="./results",

learning_rate=2e-5,

per_device_train_batch_size=16,

per_device_eval_batch_size=16,

num_train_epochs=3,

weight_decay=0.01,

logging_dir="./logs",

eval_strategy="epoch",

save_strategy="epoch"

)

# METRICS
def compute_metrics(pred):

    labels = pred.label_ids

    preds = pred.predictions.argmax(-1)

    acc = accuracy_score(labels,preds)

    return {"accuracy":acc}

# TRAINER
trainer = Trainer(

model=model,

args=training_args,

train_dataset=train_dataset,

eval_dataset=test_dataset,

compute_metrics=compute_metrics

)

# TRAIN
trainer.train()

# EVALUATE
trainer.evaluate()

# SAVE MODEL
model.save_pretrained(
"emotion_model"
)

tokenizer.save_pretrained(
"emotion_model"
)

print("MODEL TRAINED SUCCESSFULLY")

